# Site wide configuration

title: dReal
description:
logo: dReal-logo.svg
teaser:
locale:
baseurl: https://dreal.github.io
safe: true

# Jekyll configuration

sass:
    sass_dir: _sass
#    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Soonho Kong
  email: soonhok@cs.cmu.edu

exclude: ["vendor", "lib", "tutorial", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
